// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACNG2SKCErW_hqIqhzwm1_8N7CRbu95wA',
    appId: '1:555773019046:web:c695de34c85459d590c567',
    messagingSenderId: '555773019046',
    projectId: 'shashank-flutter',
    authDomain: 'shashank-flutter.firebaseapp.com',
    databaseURL: 'https://shashank-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'shashank-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmPZG9I0BfJhKxrQYFnAeU6p0tX4Ykovw',
    appId: '1:555773019046:android:f5e6233cbe0aa03090c567',
    messagingSenderId: '555773019046',
    projectId: 'shashank-flutter',
    databaseURL: 'https://shashank-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'shashank-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWDaKQ9OfoeH9CziG5chF4mW7PZhdBtXM',
    appId: '1:555773019046:ios:e54c712ae65ba0a790c567',
    messagingSenderId: '555773019046',
    projectId: 'shashank-flutter',
    databaseURL: 'https://shashank-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'shashank-flutter.appspot.com',
    androidClientId: '555773019046-7mlr7pml8ijqe5uh0jrl9h09bpnkdffc.apps.googleusercontent.com',
    iosClientId: '555773019046-plu9n9oeicn8jh73ocu5qgm7cr029ere.apps.googleusercontent.com',
    iosBundleId: 'com.example.anomAlert',
  );
}
